default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: boga

development:
  <<: *default
  database: ruby_project_dev

test:
  <<: *default
  database: ruby_project_test

production:
  <<: *default
  database: ruby_project_prod
